### ISSUE TITLE
config middleware with error

### ISSUE THREAD

**Issue by aercioneiva** [antidot-framework/getting-started-app#1]
I'm implementing a todo-app but when configuring middleware happens an error.
the aplication stay in my repository todo-app.
![error](https://user-images.githubusercontent.com/8753113/58061065-def67180-7b4a-11e9-83d1-ef01251970c4.png)

**Comment by kpicaza** [comment]
Hi, I am cloning your project to run in my environment, As a feeling, I think that it can be an issue with config cache, have you try to delete `var/cache/config-cache.php` file and reload again?

**Comment by kpicaza** [comment]
try to clear cache and running composer install, with a clean clone of your repo I have the system running 

````
bin/console config:clear-cache
composer install
````

![image](https://user-images.githubusercontent.com/1093654/58115481-71098300-7bfa-11e9-85a2-ac92f3e12386.png)

**Comment by aercioneiva** [comment]
thanks man, it works now

**Comment by kpicaza** [comment]
I opened a Slack channel for this kind of questions. If you are interested to see invitation link in twitter https://twitter.com/KPikaza/status/1130885009831813121?s=20
Thank you for supporting ;-D
