### ISSUE TITLE
It's not worked for this getting-started-app

### ISSUE THREAD

**Issue by peter279k** [antidot-framework/getting-started-app#2]
**Describe the bug**

When visiting the `localhost:8000`, it will present following error message:

```
An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

```

**To Reproduce**
- git clone git@github.com:antidot-framework/getting-started-app.git
- cd getting-started-app
- composer install
- php -S 127.0.0.1:8000 -t public

**Expected behavior**
- It's worked successfully and get the TODO list page.

**Screenshots**

![image](https://user-images.githubusercontent.com/9021747/104059905-0a066b00-5231-11eb-92f4-0f45901394f5.png)

**Additional context**
N/A.

**Comment by kpicaza** [comment]
Thank you very much for reporting, I'm updating dependencies and the readme as well,
